[package]
name = "zerda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
screenshots = "0.4.3"
tray-item = "0.7.1"

[build-dependencies]
windres = "0.2.2"